# Generated by Django 5.2.8 on 2025-11-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='destinatario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
